apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-shkm-node-sa
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-shkm-node-driver-registrar-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-shkm-node-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: csi-shkm-node-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-shkm-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io